version: "3.8"

services:
    telegram-bot:
        build: .
        container_name: finanzas_personales
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
        restart: unless-stopped
